[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=0, must-revalidate"
